import { ShieldCheckIcon } from '@heroicons/react/outline';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import InfoCard from '../components/InfoCard';
import MapComponent from '../components/MapComponent';
import PageLayout from '../components/PageLayout';
import TagsList from '../mocks/TagsList.json';
import { QueryProps, SearchResults } from '../types';

const Search = ({ searchResults }: { searchResults: SearchResults[] }) => {
  const router = useRouter();

  console.log(searchResults[0]);

  let { location, startDate, endDate, numberOfGuests }: QueryProps<string> = router.query;

  if (typeof startDate === 'string') {
    const [day, month, year] = (startDate as string).split('-');
  } else {
    return;
  }

  const range = `${startDate} — ${endDate}`;

  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/airbnb_logo.png' />
      </Head>

      <PageLayout tags={TagsList} query={{ location, startDate, endDate, numberOfGuests }}>
        <main className='flex h-[calc(100vh-160px)]'>
          <div className='bg-white flex-1 overflow-y-scroll scrollbar-hide'>
            <div className='px-6 pt-6'>
              <h1 className='text-sm text-gray-700 mb-6'>
                300+ stays {range} in {location}
              </h1>

              <div className='flex items-center gap-2 mb-6'>
                <span>
                  <ShieldCheckIcon className='w-6 h-6 text-red-500' />
                </span>
                <span className='text-sm text-gray-700'>
                  More than 1,000,000 guests have stayed in London. On average they rated their
                  stays 4.7 out of 5 stars.
                </span>
              </div>

              <div className='h-[1px] bg-gray-200 w-full mt-3 mb-6' />
            </div>

            <div className='px-6 flex flex-col'>
              {searchResults.map((item) => (
                <InfoCard item={item} key={Math.random()} />
              ))}
            </div>
          </div>

          <div className='flex-1 overflow-hidden'>
            <MapComponent searchResults={searchResults} />
          </div>
        </main>
      </PageLayout>
    </div>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const results = await fetch('https://links.papareact.com/isz').then((res) => res.json());

  console.log(results);

  return {
    props: {
      searchResults: results,
    },
  };
};
